config/routes.rb
CorpLibrary::Application.routes.draw do
  scope module: :web do
    resource :welcome, only: [:show]

    namespace :admin do
      resources :books
    end
  end

  root to: 'web/welcome#show'
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/web/admin/application_controller.rb
class Web::Admin::ApplicationController < Web::ApplicationController

end

app/controllers/web/admin/books_controller.rb
class Web::Admin::BooksController < Web::Admin::ApplicationController
  def index
    @books = Book.all
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def han(model, attribute)
    model.to_s.classify.constantize.human_attribute_name(attribute)
  end
end

app/views/layouts/web/admin/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "CorpLibrary"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "admin/application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") CorpLibrary
        .nav-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Link 1", "/path1"
            %li= link_to "Link 2", "/path2"
            %li= link_to "Link 3", "/path3"
            %li= link_to "Link 3", "/path3"

    .container
      .row
        %div{class: "col-md-#{content_for?(:sidebar) ? 9 : 12}"}
          = bootstrap_flash
          = yield
        - if content_for?(:sidebar)
          .col-md-3
            = yield :sidebar
      %footer
        %p &copy; Company 2013

app/views/layouts/web/application.html.haml
!!!
%html{lang: "en"}
  %head
    = render partial: 'layouts/web/shared/meta'
  %body.metrouicss
    .page{id: 'page-content'}
      = render partial: 'layouts/web/shared/navigation_panel'
      .page-region
        .page-region-content
          .grid
            .row
              = yield
    = render partial: 'layouts/web/shared/footer'
    = javascript_include_tag "application"

app/views/layouts/web/shared/_favicon_links.html.haml
= stylesheet_link_tag "application", :media => "all"
= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon'

app/views/layouts/web/shared/_footer.html.haml
.nav-bar{id: 'footer'}
  .nav-bar-inner{style: "padding: 10px 10px 5px;"}
    %span.element © Company 2012

app/views/layouts/web/shared/_meta.html.haml
%meta{charset: "utf-8"}
%meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
%title= content_for?(:title) ? yield(:title) : "CorpLibrary"
= csrf_meta_tags
= javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
= render partial: 'layouts/web/shared/favicon_links'

app/views/layouts/web/shared/_navigation_panel.html.haml
.nav-bar{id: 'header'}
  .nav-bar-inner.padding10
    %span.pull-menu
    %a{href: "/"}
      %span.element.brand
        %span.metro-ui-logo.place-left
        %span.name CorpLibrary
    %ul.menu
      %li= link_to "Home", "/"
      %li{"data-role" => "dropdown"}
        %a{href: "#"} Menu
        %ul.dropdown-menu
          %li= link_to "Link1", "/path1"
          %li= link_to "Link2", "/path2"
          %li.divider
          %li= link_to "Link3", "/path3"

app/views/web/admin/books/index.html.haml
.row
  .col-md-9
    %h1
      = 'Books'
  .col-md-3
    = link_to new_admin_book_path, :class => 'btn btn-success add-button' do
      = 'Add book'
      %i.icon-plus

- if @books.any?
  %table.table.table-striped
    %thead
      %tr
        %th= han(:books, :id)
        %th= han(:books, :title)
        %th= han(:books, :image)
        %th
    %tbody
      - @books.each do |book|
        %tr
          %td= book.id
          %td= book.title
          %td= book.image
          %td
            = link_to edit_admin_book_path(book) do
              %i.icon-edit
            = link_to admin_book_path(book), method: :delete do
              %i.icon-remove
  / = paginate @news, theme: 'bootstrap'
- else
  %h2= 'No Books'

app/views/web/welcome/show.html.haml
Hello library